### ISSUE TITLE
Custom normal map node can't be made correctly on blender 3.2

### ISSUE THREAD

**Issue by Ogyly** [theoldben/BlenderNormalGroups#6]
If I try to change normal maps to custom normal maps, I get this error messages.

Error: Python: Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\normal_map_to_group.py", line 106, in execute
    set_custom(getattr(mat.node_tree, 'nodes', []))
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\normal_map_to_group.py", line 84, in set_custom
    group = get_custom()
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\normal_map_to_group.py", line 79, in get_custom
    group = default_custom_nodes()
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\normal_map_to_group.py", line 259, in default_custom_nodes
    node.inputs[3].default_value = 1.0  # Height_dx
ValueError: bpy_struct: item.attr = val: sequence expected at dimension 1, not 'float'

I checked normal_map_to_group.py and if I delete these lines 

        if use_new_nodes:
            node.inputs[3].default_value = 1.0  # Height_dx
            node.inputs[4].default_value = 1.0  # Height_dy
            node.inputs[5].default_value = (0.0, 0.0, 0.0)  # Normal
        else:
            node.inputs[3].default_value = (0.0, 0.0, 0.0)  # Normal

it works. I don't know why.  I guess those are related with Bump node parameters and blender 3.2 doesn't need those anymore?

**Comment by Dyoh0** [comment]
Same issue.  This solution also works for me though.  Thanks!

**Comment by artellblender** [comment]
Replace line 143 with this:
use_new_nodes = bpy.app.version >= (2, 81) and bpy.app.version < (3, 2, 0)

**Comment by theoldben** [comment]
Thank you, Artell! Much appreciated. I added the filter criteria and made a second branch for the old version.
